# Generated by Django 5.0.1 on 2025-11-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
    ]
