# Generated by Django 5.0.1 on 2025-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorAppointment', '0002_remove_user_is_doctor_remove_user_is_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
